import React from "react";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid text-center">
        <div className="title h1 mt-4">Expense Tracker</div>
        <div className="container-fluid">
          <h1>AA</h1>
        </div>
      </div>
    </>
  );
}

export default Home;